finished but can be improved
somoskratos/test-frontend pull request #2
Opened 2019-08-06 11:53 UTC by Thrashattack

2019-08-06 19:29 UTC, somoskratos requested changes
Alguns pontos importantes do visual e arquitetura foram diferentes de nossa expectativa.
No visual, percebemos que a fonte utilizada e as cores não são as mesmas definidas do design, além de que a responsividade está quebrando tanto no mobile quanto desktop.
Na arquitetura não foi utilizado o vue-cli para gerar o projeto o que geraria um projeto mais enxuto e de mais qualidade, também não teve uma separação do que é view e o que é componente, não houve concordância em alguns nomes de variáveis  e css além dos testes unitários que não existem. As alterações do código não foram commitadas granularmente o que também não atendeu as nossas expectativas, é um projeto que precisa ser melhorado.

2019-08-06 19:29 UTC, somoskratos commented on .babelrc
> +      "presets": ["env", "stage-2"],
Todos os babels preset stage foram depreciados e não devem ser mais utilizados em novas implementações.
https://babeljs.io/docs/en/babel-preset-stage-2

2019-08-06 19:29 UTC, somoskratos commented on build/build.js
> +'use strict'
Aqui você só precisava ter gerado o projeto com o vue-cli na hora do build passar para ele essa responsabilidade. Esse tipo de configuração não é mais necessária.

2019-08-06 19:29 UTC, somoskratos commented on build/check-versions.js
> +'use strict'
Configuração já é feita de forma automática com o vue cli

2019-08-06 19:29 UTC, somoskratos commented on build/utils.js
> +'use strict'
Configuração já é feita de forma automática com o vue cli

2019-08-06 19:29 UTC, somoskratos commented on build/vue-loader.conf.js
> +'use strict'
Configuração já é feita de forma automática com o vue cli

2019-08-06 19:29 UTC, somoskratos commented on build/webpack.base.conf.js
> +'use strict'
Configuração já é feita de forma automática com o vue cli

2019-08-06 19:29 UTC, somoskratos commented on build/webpack.dev.conf.js
> +'use strict'
Configuração já é feita de forma automática com o vue cli

2019-08-06 19:29 UTC, somoskratos commented on build/webpack.prod.conf.js
> +'use strict'
Configuração já é feita de forma automática com o vue cli

2019-08-06 19:29 UTC, somoskratos commented on config/dev.env.js
> +'use strict'
Pra isso é recomentado utilizar env.local env.production etc...
https://cli.vuejs.org/guide/mode-and-env.html#modes

2019-08-06 19:29 UTC, somoskratos commented on src/components/DashClient.vue
> +        .then(data => {
Se você está resolvendo a promessa o porque do `await`?

2019-08-06 19:29 UTC, somoskratos commented on src/components/DashClient.vue
> +      await Axios.get(companysURL)
Aqui a responsabilidade da requisição poderia ser atribuida a um serviço de Http por exemplo podendo reutilizar a requisição e deixando a view somente para cuidar de assuntos da tela

2019-08-23 20:13 UTC, Thrashattack commented
Adicionado README.MD ao projeto.

2025-10-21 11:54 UTC, closed without merging